from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CalculatorWindow(object):
    def setupUi(self, CalculatorWindow):
        CalculatorWindow.setObjectName("CalculatorWindow")
        CalculatorWindow.resize(340, 426)
        CalculatorWindow.setMinimumSize(QtCore.QSize(340, 426))
        CalculatorWindow.setMaximumSize(QtCore.QSize(340, 426))
        CalculatorWindow.setStyleSheet("background-color: rgb(62, 62, 62);")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(CalculatorWindow)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 220, 340, 53))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.seven_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.seven_btn.setMinimumSize(QtCore.QSize(80, 51))
        self.seven_btn.setMaximumSize(QtCore.QSize(80, 51))
        self.seven_btn.setStyleSheet("color: rgb(255, 255, 255);")
        self.seven_btn.setObjectName("seven_btn")
        self.horizontalLayout_4.addWidget(self.seven_btn)
        self.eight_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.eight_btn.setMinimumSize(QtCore.QSize(80, 51))
        self.eight_btn.setMaximumSize(QtCore.QSize(80, 51))
        self.eight_btn.setStyleSheet("color: rgb(255, 255, 255);")
        self.eight_btn.setObjectName("eight_btn")
        self.horizontalLayout_4.addWidget(self.eight_btn)
        self.nine_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.nine_btn.setMinimumSize(QtCore.QSize(80, 51))
        self.nine_btn.setMaximumSize(QtCore.QSize(80, 51))
        self.nine_btn.setStyleSheet("color: rgb(255, 255, 255);")
        self.nine_btn.setObjectName("nine_btn")
        self.horizontalLayout_4.addWidget(self.nine_btn)
        self.devisions_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_4)
        self.devisions_btn.setMinimumSize(QtCore.QSize(80, 51))
        self.devisions_btn.setMaximumSize(QtCore.QSize(80, 51))
        self.devisions_btn.setStyleSheet("color: rgb(255, 255, 255);")
        self.devisions_btn.setObjectName("devisions_btn")
        self.horizontalLayout_4.addWidget(self.devisions_btn)
        self.horizontalLayoutWidget = QtWidgets.QWidget(CalculatorWindow)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 160, 341, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.clear_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.clear_btn.setMinimumSize(QtCore.QSize(80, 51))
        self.clear_btn.setMaximumSize(QtCore.QSize(80, 51))
        self.clear_btn.setStyleSheet("background-color: rgb(165, 29, 45);")
        self.clear_btn.setObjectName("clear_btn")
        self.horizontalLayout.addWidget(self.clear_btn)
        self.left_pt_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.left_pt_btn.setMinimumSize(QtCore.QSize(80, 51))
        self.left_pt_btn.setMaximumSize(QtCore.QSize(80, 51))
        self.left_pt_btn.setStyleSheet("color: rgb(255, 255, 255);")
        self.left_pt_btn.setObjectName("left_pt_btn")
        self.horizontalLayout.addWidget(self.left_pt_btn)
        self.right_pt_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.right_pt_btn.setMinimumSize(QtCore.QSize(80, 51))
        self.right_pt_btn.setMaximumSize(QtCore.QSize(80, 51))
        self.right_pt_btn.setStyleSheet("color: rgb(255, 255, 255);")
        self.right_pt_btn.setObjectName("right_pt_btn")
        self.horizontalLayout.addWidget(self.right_pt_btn)
        self.back_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.back_btn.setMinimumSize(QtCore.QSize(80, 51))
        self.back_btn.setMaximumSize(QtCore.QSize(80, 51))
        self.back_btn.setStyleSheet("background-color: rgb(165, 29, 45);")
        self.back_btn.setObjectName("back_btn")
        self.horizontalLayout.addWidget(self.back_btn)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(CalculatorWindow)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(0, 270, 340, 53))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.four_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.four_btn.setMinimumSize(QtCore.QSize(80, 51))
        self.four_btn.setMaximumSize(QtCore.QSize(80, 51))
        self.four_btn.setStyleSheet("color: rgb(255, 255, 255);")
        self.four_btn.setObjectName("four_btn")
        self.horizontalLayout_5.addWidget(self.four_btn)
        self.five_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.five_btn.setMinimumSize(QtCore.QSize(80, 51))
        self.five_btn.setMaximumSize(QtCore.QSize(80, 51))
        self.five_btn.setStyleSheet("color: rgb(255, 255, 255);")
        self.five_btn.setObjectName("five_btn")
        self.horizontalLayout_5.addWidget(self.five_btn)
        self.six_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.six_btn.setMinimumSize(QtCore.QSize(80, 51))
        self.six_btn.setMaximumSize(QtCore.QSize(80, 51))
        self.six_btn.setStyleSheet("color: rgb(255, 255, 255);")
        self.six_btn.setObjectName("six_btn")
        self.horizontalLayout_5.addWidget(self.six_btn)
        self.multiplication_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.multiplication_btn.setMinimumSize(QtCore.QSize(80, 51))
        self.multiplication_btn.setMaximumSize(QtCore.QSize(80, 51))
        self.multiplication_btn.setStyleSheet("color: rgb(255, 255, 255);")
        self.multiplication_btn.setObjectName("multiplication_btn")
        self.horizontalLayout_5.addWidget(self.multiplication_btn)
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(CalculatorWindow)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(0, 320, 340, 53))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.one_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.one_btn.setMinimumSize(QtCore.QSize(80, 51))
        self.one_btn.setMaximumSize(QtCore.QSize(80, 51))
        self.one_btn.setStyleSheet("color: rgb(255, 255, 255);")
        self.one_btn.setObjectName("one_btn")
        self.horizontalLayout_7.addWidget(self.one_btn)
        self.two_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.two_btn.setMinimumSize(QtCore.QSize(80, 51))
        self.two_btn.setMaximumSize(QtCore.QSize(80, 51))
        self.two_btn.setStyleSheet("color: rgb(255, 255, 255);")
        self.two_btn.setObjectName("two_btn")
        self.horizontalLayout_7.addWidget(self.two_btn)
        self.three_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.three_btn.setMinimumSize(QtCore.QSize(80, 51))
        self.three_btn.setMaximumSize(QtCore.QSize(80, 51))
        self.three_btn.setStyleSheet("color: rgb(255, 255, 255);")
        self.three_btn.setObjectName("three_btn")
        self.horizontalLayout_7.addWidget(self.three_btn)
        self.plus_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.plus_btn.setMinimumSize(QtCore.QSize(80, 51))
        self.plus_btn.setMaximumSize(QtCore.QSize(80, 51))
        self.plus_btn.setStyleSheet("color: rgb(255, 255, 255);")
        self.plus_btn.setObjectName("plus_btn")
        self.horizontalLayout_7.addWidget(self.plus_btn)
        self.verticalLayoutWidget = QtWidgets.QWidget(CalculatorWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 110, 341, 56))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.result_input_lbl = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.result_input_lbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.result_input_lbl.setText("")
        self.result_input_lbl.setReadOnly(True)
        self.result_input_lbl.setObjectName("result_input_lbl")
        self.verticalLayout.addWidget(self.result_input_lbl)
        self.error_lbl = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.error_lbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.error_lbl.setObjectName("error_lbl")
        self.verticalLayout.addWidget(self.error_lbl)
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(CalculatorWindow)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(0, 370, 341, 53))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.minus_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.minus_btn.setMinimumSize(QtCore.QSize(80, 51))
        self.minus_btn.setMaximumSize(QtCore.QSize(80, 51))
        self.minus_btn.setStyleSheet("color: rgb(255, 255, 255);")
        self.minus_btn.setObjectName("minus_btn")
        self.horizontalLayout_8.addWidget(self.minus_btn)
        self.zero_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.zero_btn.setMinimumSize(QtCore.QSize(80, 51))
        self.zero_btn.setMaximumSize(QtCore.QSize(80, 51))
        self.zero_btn.setStyleSheet("color: rgb(255, 255, 255);")
        self.zero_btn.setObjectName("zero_btn")
        self.horizontalLayout_8.addWidget(self.zero_btn)
        self.parcent_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.parcent_btn.setMinimumSize(QtCore.QSize(80, 51))
        self.parcent_btn.setMaximumSize(QtCore.QSize(80, 51))
        self.parcent_btn.setStyleSheet("color: rgb(255, 255, 255);")
        self.parcent_btn.setObjectName("parcent_btn")
        self.horizontalLayout_8.addWidget(self.parcent_btn)
        self.equals_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget_8)
        self.equals_btn.setMinimumSize(QtCore.QSize(80, 51))
        self.equals_btn.setMaximumSize(QtCore.QSize(80, 51))
        self.equals_btn.setStyleSheet("color: rgb(255, 255, 255);")
        self.equals_btn.setObjectName("equals_btn")
        self.horizontalLayout_8.addWidget(self.equals_btn)
        self.expression_lbl = QtWidgets.QLabel(CalculatorWindow)
        self.expression_lbl.setGeometry(QtCore.QRect(0, 80, 339, 24))
        self.expression_lbl.setStyleSheet("color: rgb(255, 255, 255);")
        self.expression_lbl.setText("")
        self.expression_lbl.setObjectName("expression_lbl")

        self.retranslateUi(CalculatorWindow)
        QtCore.QMetaObject.connectSlotsByName(CalculatorWindow)

    def retranslateUi(self, CalculatorWindow):
        _translate = QtCore.QCoreApplication.translate
        CalculatorWindow.setWindowTitle(_translate("CalculatorWindow", "Calculator"))
        self.seven_btn.setText(_translate("CalculatorWindow", "7"))
        self.eight_btn.setText(_translate("CalculatorWindow", "8"))
        self.nine_btn.setText(_translate("CalculatorWindow", "9"))
        self.devisions_btn.setText(_translate("CalculatorWindow", "/"))
        self.clear_btn.setText(_translate("CalculatorWindow", "C"))
        self.left_pt_btn.setText(_translate("CalculatorWindow", "("))
        self.right_pt_btn.setText(_translate("CalculatorWindow", ")"))
        self.back_btn.setText(_translate("CalculatorWindow", "<-"))
        self.four_btn.setText(_translate("CalculatorWindow", "4"))
        self.five_btn.setText(_translate("CalculatorWindow", "5"))
        self.six_btn.setText(_translate("CalculatorWindow", "6"))
        self.multiplication_btn.setText(_translate("CalculatorWindow", "*"))
        self.one_btn.setText(_translate("CalculatorWindow", "1"))
        self.two_btn.setText(_translate("CalculatorWindow", "2"))
        self.three_btn.setText(_translate("CalculatorWindow", "3"))
        self.plus_btn.setText(_translate("CalculatorWindow", "+"))
        self.minus_btn.setText(_translate("CalculatorWindow", "-"))
        self.zero_btn.setText(_translate("CalculatorWindow", "0"))
        self.parcent_btn.setText(_translate("CalculatorWindow", "%"))
        self.equals_btn.setText(_translate("CalculatorWindow", "="))